name: Install DevOps Tools on EC2

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'tools-installation/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  get-ec2-ip:
    name: 'Get EC2 IP'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Get EC2 IP from state
        id: ec2-ip
        run: |
          terraform -chdir=infrastructure init
          IP=$(terraform -chdir=infrastructure output -raw instance_public_ip)
          echo "ip=$IP" >> $GITHUB_OUTPUT

  install-tools:
    name: 'Install Tools'
    runs-on: ubuntu-latest
    needs: get-ec2-ip

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Install Terraform
        run: |
          scp -o StrictHostKeyChecking=no tools-installation/install_terraform.sh ubuntu@${{ needs.get-ec2-ip.outputs.ip }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.get-ec2-ip.outputs.ip }} "chmod +x /home/ubuntu/install_terraform.sh && /home/ubuntu/install_terraform.sh"

      - name: Install Docker
        run: |
          scp -o StrictHostKeyChecking=no tools-installation/install_docker.sh ubuntu@${{ needs.get-ec2-ip.outputs.ip }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.get-ec2-ip.outputs.ip }} "chmod +x /home/ubuntu/install_docker.sh && /home/ubuntu/install_docker.sh"

      - name: Install SonarQube
        run: |
          scp -o StrictHostKeyChecking=no tools-installation/install_sonarqube.sh ubuntu@${{ needs.get-ec2-ip.outputs.ip }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.get-ec2-ip.outputs.ip }} "chmod +x /home/ubuntu/install_sonarqube.sh && /home/ubuntu/install_sonarqube.sh"

      - name: Install OWASP ZAP
        run: |
          scp -o StrictHostKeyChecking=no tools-installation/install_owasp.sh ubuntu@${{ needs.get-ec2-ip.outputs.ip }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.get-ec2-ip.outputs.ip }} "chmod +x /home/ubuntu/install_owasp.sh && /home/ubuntu/install_owasp.sh"

      - name: Install Trivy
        run: |
          scp -o StrictHostKeyChecking=no tools-installation/install_trivy.sh ubuntu@${{ needs.get-ec2-ip.outputs.ip }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.get-ec2-ip.outputs.ip }} "chmod +x /home/ubuntu/install_trivy.sh && /home/ubuntu/install_trivy.sh"

      - name: Install Helm
        run: |
          scp -o StrictHostKeyChecking=no tools-installation/install_helm.sh ubuntu@${{ needs.get-ec2-ip.outputs.ip }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.get-ec2-ip.outputs.ip }} "chmod +x /home/ubuntu/install_helm.sh && /home/ubuntu/install_helm.sh"

      - name: Install Kubernetes
        run: |
          scp -o StrictHostKeyChecking=no tools-installation/install_kubernetes.sh ubuntu@${{ needs.get-ec2-ip.outputs.ip }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.get-ec2-ip.outputs.ip }} "chmod +x /home/ubuntu/install_kubernetes.sh && /home/ubuntu/install_kubernetes.sh"

      - name: Install ArgoCD
        run: |
          scp -o StrictHostKeyChecking=no tools-installation/install_argocd.sh ubuntu@${{ needs.get-ec2-ip.outputs.ip }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.get-ec2-ip.outputs.ip }} "chmod +x /home/ubuntu/install_argocd.sh && /home/ubuntu/install_argocd.sh"
