name: Security Scanning

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  security-scan:
    name: 'Run Security Scans'
    runs-on: ubuntu-latest
    needs: install-tools

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get EC2 IP
        id: ec2-ip
        run: |
          IP=$(terraform -chdir=infrastructure output -raw instance_public_ip)
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Run SonarQube Scan
        run: |
          scp -r -o StrictHostKeyChecking=no src ubuntu@${{ steps.ec2-ip.outputs.ip }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.ec2-ip.outputs.ip }} "docker exec sonarqube sonar-scanner -Dsonar.projectKey=ecommerce -Dsonar.sources=/home/ubuntu/src -Dsonar.host.url=http://localhost:9000 -Dsonar.login=admin -Dsonar.password=admin"

      - name: Run OWASP ZAP Scan
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.ec2-ip.outputs.ip }} "/opt/zaproxy/zap.sh -cmd -quickurl http://localhost:5000 -quickprogress -quickout /home/ubuntu/zap-report.html"

      - name: Run Trivy Scan
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.ec2-ip.outputs.ip }} "trivy fs --security-checks vuln,config /home/ubuntu/src > /home/ubuntu/trivy-report.txt"
